### ISSUE TITLE
Relations and Backend Plugins 

### ISSUE THREAD

**Issue by Cleanse** [ivandoric/Making-Websites-With-October-CMS#18]
I'm curious if you take on work on the side? I'm looking to setup an OctoberCMS plugin for a tournament system.

**Comment by ivandoric** [comment]
Hi @Cleanse , no I don't, and also I'm not a October expert. So I don't think I would be very good at that kind of job :)

**Comment by Cleanse** [comment]
Okay, thanks for the reply!
