### ISSUE TITLE
front end form

### ISSUE THREAD

**Issue by Prasanthkathiresan** [ivandoric/Making-Websites-With-October-CMS#23]
##### Expected behavior
(Describe expected behavior here)

##### Actual behavior
(Describe actual behavior here)

##### Reproduce steps
(Describe the steps to reproduce the problem here)

##### October build
(October build number)
i have problem in front end form in back end it store in database but in front end with i click save it will not save any data in database what to do please sir my humble request please create separate form design and how to insert in database please do clear video for me please sir

**Comment by ivandoric** [comment]
Hi, sorry but I can't help you without more information.

**Comment by Prasanthkathiresan** [comment]
``
<?php namespace Bizbee\Details\Components;

use Cms\Classes\ComponentBase;
use Input;
use Bizbee\Details\Models\Detail;

class DetailForm extends ComponentBase
{


	public function componentDetails(){
		return[
			'name'=>'Detail Form',
			'description'=>'Simple detail form' 

		];
	}
	public function onSave(){
		$detail=new Detail;
		$detail->name=Input::get('name');
		$detail->description=Input::get('description');

$detail->year=Input::get('year');
$detail->save();



	}
}


ivandoric this is not working for me please help me

**Comment by Prasanthkathiresan** [comment]
`<?php namespace Bizbee\Details\Components;

use Cms\Classes\ComponentBase;
use Input;
use Bizbee\Details\Models\Detail;

class DetailForm extends ComponentBase
{


	public function componentDetails(){
		return[
			'name'=>'Detail Form',
			'description'=>'Simple detail form' 

		];
	}
	public function onSave(){
		$detail=new Detail;
		$detail->name=Input::get('name');
		$detail->description=Input::get('description');

$detail->year=Input::get('year');
$detail->save();



	}
}`

**Comment by ivandoric** [comment]
This should work. Are you getting any errors? Check the network tab in your Devtools. Also, check if all the fields in your form are correctly named.

**Comment by Prasanthkathiresan** [comment]
Sir video 20 is not working properly that is only I have problem in
database sir

**Comment by ivandoric** [comment]
The video is working properly, as you could see, well, in the video. Your code is not working properly. That is the problem. And I asked you if you got any errors, you still haven't answered me.

**Comment by Prasanthkathiresan** [comment]
Hi sir I installed user plugin what step you Do that I do sir but when
register that information not store in the backend send what to do help me
and guide me sir please

**Comment by Prasanthkathiresan** [comment]
nothing error will show sir thats the problem for me

**Comment by ivandoric** [comment]
If something is not saving to your database, then you would have to have some error. Did you check the network tab in your development tools. I can't help you if I don't know what kind of error you are getting.

**Comment by Prasanthkathiresan** [comment]
Development tool I send snapshot to you sir please that sir

**Comment by Prasanthkathiresan** [comment]
Please sir don't tell I will not help you please help me sir

**Comment by Prasanthkathiresan** [comment]
sir thank you so much its working i did in script jquery path in that you
tell see in network tab i cleared that now its works thank you much  your
support and guides if any help need i will ask futher work please help me
sir

**Comment by ivandoric** [comment]
Glad you figured it out :) ... Closing this issue.

**Comment by Prasanthkathiresan** [comment]
Hi,sir i want help from you  how to generate an id along with string
e.g(PT001) like this how to do ?

**Comment by ivandoric** [comment]
Where do you want to generate it? In your template? Can't you do something like this for example:

```twig
PT{{ post.id }}
```

In your loop?

**Comment by Prasanthkathiresan** [comment]
sir can you please tell us how to retrieve data from database in our
frontend form (i.e select * from table where id='1') in october cms

**Comment by ivandoric** [comment]
You don't do that. You should be using eloquent. So you query database this way: https://laravel.com/docs/5.7/queries

And you can put that in the PHP block of the page where the form is rendered. Some examples for PHP block: https://www.youtube.com/watch?v=Ukcf8tgQUXc

**Comment by Prasanthkathiresan** [comment]
Hi Sir, good evening. How can I generate a report that is when I give a
patient I'd and click view button then it has to display that particular
patient details from the database. I attach a image that how I want to
display my database record in the front end form..
