### ISSUE TITLE
How do i render subcategories when a category is clicked?

### ISSUE THREAD

**Issue by Corymillz** [ivandoric/Making-Websites-With-October-CMS#25]
I am currently working on a project that has categories and subcategories and i used octobercms nested tree to have parents_id = 0 for categories and parent_id>0 for subcategories under each category. It all works fine and good using reorder in the back-end. When i drag the list component to my page it shows up  all the Categories with subcategories in one long list. I was able to show only the categories using the code below

`public function scopeCategory($query)
    {        
        return $query->take(10)->where('parent_id',0);

        }`

Now only the main categories show up without the subcategories.

Now what i want to implement but not sure how to go about it is to show subcategories belonging to a category when that category is clicked. For example if i click on say Agriculture, all the subcategories under agriculture shows up or when i click Fashion all the subcategories under fashion shows up.

I tried connecting the list page to a details page with an effort to show all subcategories belonging to a clicked category but non of the things i have tried worked.

**Additional Info**

Below is a picture of how it renders without scopeCategory
![screenshot 33](https://user-images.githubusercontent.com/42346851/53286422-93762800-3701-11e9-8a94-e092e8a36cc6.png)

Applying scopeCategory
![screenshot 34](https://user-images.githubusercontent.com/42346851/53286440-e5b74900-3701-11e9-9e11-ded1532ae055.png)

I am using the Current up to date version of Octobercms

**Comment by ivandoric** [comment]
Ok, so I have something similar on my site. So when you go to [that site](https://watch-learn.com/) if you click Series and then click on one of the series you will get only videos that belong o that series. 

Now, I don't know exactly what your setup is, I see that you  are using components etc. On my site I'm not using components and I'm just getting all the queries from PHP block: [This is the video about PHP blocks](https://www.youtube.com/watch?v=Ukcf8tgQUXc)

And on the series page I have something like this in PHP block:

```php
$this['videos'] = WatchLearn\Videos\Models\Video::whereHas('series', function ($query) {
        $query->where('slug', '=', $this->param('slug'))->where('published', true);
    })->orderBy('created_at', 'asc')->get();
```

So I'm calling all the videos, and then filtering only the videos that have have series connected to them with the specific slug (usually the slug of the page being viewed) `$this->param('slug')` ...

I guess you can make something similar for your categories, if they are connected in some way. If this doesn't help you, try asking on October forums or StackOverflow.

**Comment by Corymillz** [comment]
Thank you very much. You pointed me towards the right direction. I am now fully using the php block. Just one little thing.

I am using this query to get the children of each category
            `$this['children'] = Cat::all()->children;`
But it only gets the subcategories of of the first category and the same subcategories appear for all other categories. Any ideas on how t fix this?

**Comment by ivandoric** [comment]
Hmmm, this is not right. Because with `Cat::first()` you are only calling the first category in database. Check this page out: https://laravel.com/docs/5.7/queries this is all applicable to October.

I think you should do something like: `Cat::with('children')->get();` 

As I said I don't know your setup so this might not work. But with this should get you all your categories, and to every category there would be attached list of children. And then you can easily iterate through them with 2 foreach loops.

**Comment by Corymillz** [comment]
It works perfectly but how to apply the two foreach iteration is what i have been banging my head about. One foreach does the job of eager loading everything.

**Comment by ivandoric** [comment]
Well, something like this.

```twig
{% for category in categories %}
...
...
    {% for child in category.children %}
        ...
        ...
    {% endfor %}

{% endfor %}

```

This should be it if you are getting your categories with subcategories.

**Comment by Corymillz** [comment]
Finally got it to work with this 
`$slug = $this->param('slug');`

` $this['child'] = Cat::whereHas('parent', function ($query) use ($slug) {
                  $query->where('slug',$slug);
               })->get();`

and this as my foreach
` {% for child in child %}

<h6>{{ child.cat_title }}</h6>

 {% else %}

  <li class="no-data">{{ noRecordsMessage }}</li>



 {% endfor %}`

Thanks for your assistance

**Comment by ivandoric** [comment]
Glad you got it to work :) Closing this issue.
