### ISSUE TITLE
How to create table with two primary key in same table for blongstomany relation?

### ISSUE THREAD

**Issue by FarzinBidokhti** [ivandoric/Making-Websites-With-October-CMS#28]
##### Expected behavior
(Hi, i have trainingevent model and discount model. The trainingevent model can have many discounts. When I create synon_trainingevent_discounts_events table, i get this error 
" SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'synon_trainingevent_discounts_events_event_id_discount_id_primary' is too long (SQL: alter table `synon_trainingevent_discounts_events` add primary key `synon_trainingevent_discounts_events_event_id_discount_id_primary`(`event_id`, `discount_id`)) "
  )

In This table i have event_id and discount_id

##### Actual behavior
(Describe actual behavior here)

##### Reproduce steps
(Describe the steps to reproduce the problem here)

##### October build
(October build number)

**Comment by ivandoric** [comment]
I'm not an expert in these types of errors, but I can see that it says: `Identifier name 'synon_trainingevent_discounts_events_event_id_discount_id_primary' is too long`

Seems to me that `synon_trainingevent_discounts_events_event_id_discount_id_primary` is too long. Although I've never seen this error.

Try changing that identifier to something shorter, and if that doesn't try asking at October forums. As I've said, I don't know much about databases, so I can't offer more help on the matter.
