### ISSUE TITLE
Uploading my project to host

### ISSUE THREAD

**Issue by FarzinBidokhti** [ivandoric/Making-Websites-With-October-CMS#36]
Hi 
I saw this 'Deploying To Shared Hosting' episode in your site and i uploaded my project to my host according to your tutorial, my problem is i can see my theme without any error but i cant see the test.test/backend page, i get this error:
'Page not found'
Why i can see this url 'test.test' but i can't see this page 'test.test/backend'?
Please help me.

**Comment by ivandoric** [comment]
What kind of database are you using?

**Comment by FarzinBidokhti** [comment]
I'm useing mysql.

**Comment by ivandoric** [comment]
First of all I don't understand how you can have .test domain on your host. That should only be available on your localhost, but ok. This error can come up if you didn't setup the database on your hosting, and changed the configuration to access that database. Did you do that?

**Comment by FarzinBidokhti** [comment]
let me saying you what was i do?
1) I create .env file with this command: php artisan october:env
2) I upload my project to host with git-ftp
3) I create new database on host and export my local database and import it on mysql in host
4) I create new .env file in host and config it according to host information.
5) I test the test.test url i can see my october theme but when i test this url 'test.test/backend' i get this error: not found.
6) Now i delete my project in host and i zip my project, i want to uploade zip file by filezilla.

**Comment by FarzinBidokhti** [comment]
Mr @ivandoric the above problem was solved. but i have some new errors:
i have a order plugin that it have belongsTo relation to orderType model in it's model:
    public function orderType()
    {
        return $this->belongsTo('synon\baseinfo\models\orderType');
    }
but when i want run order plugin i get this error:
Class 'synon\baseinfo\models\orderType' not found
/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php line 653
 How can i fixed it 
or my second problem is in my another plugin i use partial but i get this error:
not found /public_html\plugins\synon\product\models\product\_discount_percent.htm

Note: I don't have any problem in local.
Please help me.

**Comment by FarzinBidokhti** [comment]
My problem Fixed.
