### ISSUE TITLE
Load related models in "Ajax Frontend Filters"

### ISSUE THREAD

**Issue by yabasha** [ivandoric/Making-Websites-With-October-CMS#37]
##### Expected behavior
I made a similar page to the one titled "[Ajax Frontend Filters](https://www.youtube.com/watch?v=Pz3XgasUN8g&list=PLUBR53Dw-Ef-X-_A1KLy41r2QArCBy4rM&index=42&t=1349s)" 

I put category and subcategory both are working fine but subcategory lists all subcategories but I want to show related subcategories to the selected category.
![image](https://user-images.githubusercontent.com/932321/87015440-18b68b80-c1d6-11ea-9c99-163bed73aafe.png)

Category `$belongsToMany` subcategories and Subcategory `$belongsToMany` categories

I get the subcategories in `onStart()` function as below
```
$this['categories'] = Category::all()->sortBy('name');
$this['subcategories'] = SubCategory::all()->sortBy('name');
```

I put the subcattegories select box in a partial to update with each AJAX filter:
```
{{ form_ajax('onFilterDocuments', { update: { 'documents/documents': '#partialDocuments', 'documents/paginate': '#partialPaginate', 'documents/subcategory': '#partialSubcategory' }, id: 'FilterForm' }) }}
.
.
.
<div id="partialSubcategory">
        {% partial 'documents/subcategory' %}
</div>
```

how can I make sub categories updated once select a new category?

Please Advice,

##### October build
465

**Comment by ivandoric** [comment]
I don't know, sorry. As I've said on Twitter, I'm a bit rusty on October, haven't used it in a while. Try October forums or official Slack channel.

**Comment by yabasha** [comment]
I kept working on it till I come up with the following solution:

Because there is a relation between `Category` and `SubCategory` I could get all the related `subcategories` from the selected `category` as following:

In `prepareVars` function I get the value of `Filter[category]` select box, to get the id of the selected category, then i set the `subcategories` variable to be
```
$selectedCategory = Input('Filter[category]','');// get the value from the submitted requestest

$this['subcategories'] = Category::find($selectedCategory) ? Category::find($selectedCategory)->subcategories()->withCount('documents')->get()->sortBy('name') : SubCategory::relatedDocuments()->get()->sortBy('name');
```
Here I check if there is a selected value then I assign the result to the variable using ternary operator.

I will keep this open if someone can get a better solution.

I hope this may help someone,

Below is the full coded function which is in htm page as the video showed:

```
function prepareVars() {

    $options = post('Filter', []);

    $this['currentSubcategory'] = Input('selected-subcategory', '');

    $selectedCategory = Input('Filter[category]','');

    $this['documents'] = Document::listFrontend($options);
    $this['categories'] = Category::relatedDocuments()->get()->sortBy('name');

    $this['subcategories'] = Category::find($selectedCategory) ? Category::find($selectedCategory)->subcategories()->withCount('documents')->get()->sortBy('name') : SubCategory::relatedDocuments()->get()->sortBy('name');

    $this['tags'] = Tag::all()->sortBy('name');

    $this['sortOptions'] = Document::$allowedSortingOptions;

    $this['pages'] = $this['documents']->lastPage();
    $this['currentPage'] = $this['documents']->currentPage();
}
```

**Comment by ivandoric** [comment]
Glad you figured it out 🎉  Good job! :)
