### ISSUE TITLE
using List Switch with Relation Manager

### ISSUE THREAD

**Issue by jumpshotink** [ivandoric/Making-Websites-With-October-CMS#38]
Hi - great series for October.

I am using the List Switch with a relation manager and I get an error:

`AJAX handler 'onSwitchInetisListField' was not found.`

I have a models called Project and Time where the time sheet is related to the project with project_id. Is there a way to get the ajax functionality working in the relation manager?

Thanks in advance.

**Comment by ivandoric** [comment]
I honestly don't know. Try October forums for that.

**Comment by jumpshotink** [comment]
Hi - thanks for responding. I found the following on List Switch github page: 
https://github.com/inetis-ch/oc-ListSwitch-plugin/issues/7
Hope this helps others.
