### ISSUE TITLE
Better Relations

### ISSUE THREAD

**Issue by stevwarner** [ivandoric/Making-Websites-With-October-CMS#4]
Your videos are a great tool for developers on this framework. I think you've done really great things on your video series. That you've now touched base about "filters" is a super gift to all of us! What I think would be a great subject for everybody would be an in-depth look at database relations (the October way) with some videos about how to code for "database relation manager" where there are several fields to be included (selected) from a table when there are more than one tables involved. The coding is daunting and making it work takes many attempts.  Thank you!

**Comment by ivandoric** [comment]
Glad you like the videos. Somebody already asked that I do relation manager. I will see what I can do. It's a good idea for video.

**Comment by ipokkel** [comment]
This would be awesome! 
BTW, Your awesome videos inspired me to start experimenting with October and to pick up coding again after being out of action for many many years. People like you make the world a great place.

**Comment by ivandoric** [comment]
Video about relation manager is available [here](https://www.youtube.com/watch?v=ssU7JdS3TII) guys.

**Comment by stevwarner** [comment]
it would be great to give you a one time donation, maybe you can accept via paypal?

**Comment by ivandoric** [comment]
@stevwarner I have a Patreon page, so you can donate there :) . You can opt out whenever you want. https://www.patreon.com/watchlearn
