### ISSUE TITLE
Frontend form not saving to database...

### ISSUE THREAD

**Issue by maartenmachiels** [ivandoric/Making-Websites-With-October-CMS#5]
##### Expected behavior
Save contactform entries to the database

##### Actual behavior
The saving of the contactform does not work.  Component 'Chocolata\Rsvp\Components\Rsvp' does not contain a save method on line 271 of /var/www/vhosts/xxxxxxxxx.be/httpdocs/modules/cms/classes/ComponentBase.php

##### Reproduce steps
Filled out a contact form after adding these lines in the success handler of the form:
            $rsvp = new Rsvp();
            $rsvp->name = $vars['name'];
            $rsvp->email = $vars['email'];
            $rsvp->remarks = $vars['remarks'];
            $rsvp->optin_ceremonie = $vars['optin_ceremonie'];
            $rsvp->optin_burgerlijk = $vars['optin_burgerlijk'];
            $rsvp->optin_feest = $vars['optin_feest'];
            $rsvp->save();

##### October build
419

Hi Ivan, as requested on YouTube, some extra details here. My component is called Rsvp.php and is based on your tutorials of the ContactForm.php.  

```
<?php namespace Chocolata\Rsvp\Components;

use Cms\Classes\ComponentBase;
use Input;
use Mail;
use Validator;
use Redirect;
use ValidationException;
use Flash;
//use Chocolata\Rsvp\Models\Rsvp;


class Rsvp extends ComponentBase {
    public function componentDetails()
    {
        return [
            'name' => 'RSVP Form',
            'description' => 'Simple RSVP form to gather responses'
        ];
    }
    public function onSend() {
        $data = post();
        $rules = [
            'name' => 'required|min:5',
            'email' => 'required|email'
        ];
        $validator = Validator::make($data, $rules);
        if($validator->fails()){
            throw new ValidationException($validator);
        } else {

            // Prepare the variables
            $vars = [
                        'name'              => Input::get('name'),
                        'email'             => Input::get('email'),
                        'remarks'           => Input::get('remarks'),
                        'optin_ceremonie'   => (Input::get('optin_ceremonie') ? 1 : 0),
                        'optin_feest'       => (Input::get('optin_feest') ? 1 : 0),
                        'optin_burgerlijk'  => (Input::get('optin_burgerlijk') ? 1 : 0)
                    ];

            // Send a mail
            Mail::send('chocolata.rsvp::mail.message', $vars, function($message) {
                $message->to('xxxx@xxx.be', 'XXX XXX');
                $message->subject('Nieuwe RSVP - '.Input::get('name'));
                $message->replyTo(Input::get('email'),Input::get('name'));
            });


            // Add it to the database
            $rsvp = new Rsvp();
            $rsvp->name = $vars['name'];
            $rsvp->email = $vars['email'];
            $rsvp->remarks = $vars['remarks'];
            $rsvp->optin_ceremonie = $vars['optin_ceremonie'];
            $rsvp->optin_burgerlijk = $vars['optin_burgerlijk'];
            $rsvp->optin_feest = $vars['optin_feest'];
            $rsvp->save();

            //return Redirect::back();
            Flash::success('Uw RSVP werd met succes vastgelegd!');

            return ['#result' => $this->renderPartial('rsvp::success'), [

            ]];
        }
    }
}
```

Please note that if I uncomment `//use Chocolata\Rsvp\Models\Rsvp;` I get an error stating that the model is already included. What could I be overlooking?

Example is here: https://xxxxxx.be/rsvp

Thanks for looking at this, really appreciate it!

**Comment by ivandoric** [comment]
Hmm, first of all why is your "use" for the model commented out:  `use Chocolata\Rsvp\Models\Rsvp;` ?

Also I don't think you can create new Rsvp model by doing `$rsvp = new Rsvp();`

It should be without parenthesis `$rsvp = new Rsvp;` and this will only work if the `use` for the model is not commented out.

If this doesn't work for some reason, try this:

``` 
Rsvp::create([
   'name' => $vars['name'],
   'email' => $vars['email'],
   ...
]);
```
Of course you have to uncomment  `use`.

**Comment by maartenmachiels** [comment]
Hi Ivan

Thanks. I added both of your modifications. I still get the same error message. Now it says 'Chocolata\Rsvp\Components\Rsvp' does not contain a create method

I commented out `use Chocolata\Rsvp\Models\Rsvp;` because I keep getting the error below:

![exception](https://cloud.githubusercontent.com/assets/3584586/26143468/63de42f4-3ae5-11e7-8222-9ee2f5fb5f88.png)

**Comment by ivandoric** [comment]
There is something wrong with your namespaces. It's trying to use: Chocolata\Rsvp\Components\Rsvp instead of Chocolata\Rsvp\Models\Rsvp do you even have Rsvp model created? Or just this component?

**Comment by maartenmachiels** [comment]
Hi Ivan

Thank you for your response. I have created some models via the Builder plugin. This is what I have under models at the moment:
![models](https://cloud.githubusercontent.com/assets/3584586/26144153/0a0d9fa6-3ae8-11e7-81ac-e2a33a75688b.png)

In your frontend form, you had Actors. And then you had ActorForm as a separate model. So when you used the Actor model, there was no issue. 

I'm new at this :-) as you can see

**Comment by ivandoric** [comment]
Can you show me your plugins folder, uncolapse it so that I can see all the models components etc. that you have. I don't think I made a ActorForm model in my videos, actorForm is just a component. And it uses the Actor model.

**Comment by maartenmachiels** [comment]
With pleasure. See below please:
![plugins](https://cloud.githubusercontent.com/assets/3584586/26144534/8766fd70-3ae9-11e7-870b-46952535b7a4.PNG)

**Comment by ivandoric** [comment]
Ok, so you have component called Rsvp and a model called Rsvp. That is not right.  Try changing the name of your component. Remember to change all the references of it in the files (eg. Plugin.php).

**Comment by maartenmachiels** [comment]
Thank you Ivan. So namingconventionwise, it should be something like RsvpForm, yes?

**Comment by ivandoric** [comment]
I don't know if there is naming convention for components, but I'm pretty sure that they should not be called the sam as the models :)

**Comment by maartenmachiels** [comment]
;-) okay - I'll give that a try later on today and let you know. Thanks for
your patience :-D

--
<http://chocolata.be>

Maarten Machiels
Webdesigner - Webdeveloper

T: +32 (0)474 82 38 61 <0032474823861>
W: www.chocolata.be <http://chocolata.be/>
E: maarten@chocolata.be


2017-05-17 10:22 GMT+02:00 Ivan Dorić <notifications@github.com>:

**Comment by maartenmachiels** [comment]
;-) okay - I'll give that a try later on today and let you know. Thanks for your patience :-D

**Comment by ivandoric** [comment]
No problem @maartenmachiels , let me know how it goes.

**Comment by maartenmachiels** [comment]
Ivan, as for now, I cannot get it to work. I think I'm making a fundamental error somewhere. I'll do some more self study with your videos and get back to this later if I solve it.

**Comment by ivandoric** [comment]
@maartenmachiels I made a quote form a while ago for the company I used to work for. Check this code, maybe that can help you. It does pretty much the same thing as your form, sends e-mail, and saves stuff to the database:


```php
<?php namespace Gauss\Quotes\Components;

use Cms\Classes\ComponentBase;
use Input;
use Mail;
use Validator;
use Redirect;
use Gauss\Quotes\Models\Quote;
use ValidationException;
use Flash;
use AjaxException;

class FormQuote extends ComponentBase
{

    public function componentDetails(){
        return [
            'name' => 'Form Quote',
            'description' => 'Form Quote'
        ];
    }


    public function onSend(){
        
        $data = post();
        //dd($data);

        $rules = [
            'name' => 'required',
            'email' => 'required|email',
            'g-recaptcha-response' => 'required'
        ];

        $validator = Validator::make($data, $rules);

        if($validator->fails()){

            throw new ValidationException($validator);
            
        } else {
            $vars = Input::all();

            $quote = new Quote;

            // Save type as a string
            if(!empty(Input::get('type'))){
                $type = Input::get('type');
                $typestring = '';
                foreach($type as $typesingle){
                    $typestring .= $typesingle . ', ';
                }

                $quote->type = $typestring;
            }

            $quote->name = Input::get('name');
            $quote->email = Input::get('email');
            $quote->company = Input::get('company');
            $quote->web = Input::get('web');
            $quote->budget = Input::get('budget');
            $quote->deadline = date("Y-m-d", strtotime(Input::get('deadline')));
            $quote->description = Input::get('description');
            $quote->save();

            Mail::send('gauss.quotes::mail.message', $vars, function($message) use ($vars) {
                $message->to('xxxxxxxx', 'xxxxxxxxx')->replyTo($vars['email'])->subject('New message from Quote Form');
            });

            //Flash::success("Thank you for your interest! We'll get back to you ASAP!");
        }
    }

}
```

Hope this helps you.

**Comment by maartenmachiels** [comment]
Thank you Ivan - this is very very helpful. As I can see right now, it probably is due to the namings of my components and models. Will report soon.

**Comment by Prasanthkathiresan** [comment]
maarten, fornt end form databse is working for you please help me
